Second attempt to use SPI
Initially I wanted to avoid the DMA peripheral just to keep the
trait bounds as simple as possible, but for some reason, the
SpiDevice<Spi-without-Dma...> did not implement the
required bounds. Anyhow, it's commented out in the code.
But the compiler suggested that the Spi with DMA does provide
the trait impl!

So I went on to use Spi with DMA and I got the following:
```
error[E0277]: `*mut u8` cannot be sent between threads safely
   --> src/main.rs:253:72
    |
253 |           .start_app_core(unsafe { &mut *addr_of_mut!(APP_CORE_STACK) }, move || {
    |  __________--------------________________________________________________^
    | |          |
    | |          required by a bound introduced by this call
254 | |             static EXECUTOR: StaticCell<Executor> = StaticCell::new();
255 | |             let executor = EXECUTOR.init(Executor::new());
256 | |             executor.run(|spawner| {
257 | |                 spawner.spawn(motion_analysis(spi_dev, sender, flag)).unwrap();
258 | |             });
259 | |         })
    | |_________^ `*mut u8` cannot be sent between threads safely
    |
    = note: the full trait has been written to '/home/being/code/practice/rust/test-xtensa-nostd/target/xtensa-esp32s3-none-elf/debug/deps/test_xtensa_nostd-aafbfb69abc1d303.long-type-15121438269329452012.txt'
    = help: within `SpiDma<'static, SPI2, Channel<0>, FullDuplexMode, Async>`, the trait `core::marker::Send` is not implemented for `*mut u8`, which is required by `{closure@src/main.rs:253:72: 253:79}: core::marker::Send`
note: required because it appears within the type `esp_hal::dma::DmaDescriptor`
   --> /home/being/.cargo/registry/src/index.crates.io-6f17d22bba15001f/esp-hal-0.19.0/src/dma/mod.rs:76:12
    |
76  | pub struct DmaDescriptor {
    |            ^^^^^^^^^^^^^
    = note: required because it appears within the type `[esp_hal::dma::DmaDescriptor]`
    = note: required because it appears within the type `&'static mut [esp_hal::dma::DmaDescriptor]`
note: required because it appears within the type `esp_hal::dma::DescriptorChain`
   --> /home/being/.cargo/registry/src/index.crates.io-6f17d22bba15001f/esp-hal-0.19.0/src/dma/mod.rs:522:12
    |
522 | pub struct DescriptorChain {
    |            ^^^^^^^^^^^^^^^
note: required because it appears within the type `SpiDma<'static, SPI2, Channel<0>, FullDuplexMode, Async>`
   --> /home/being/.cargo/registry/src/index.crates.io-6f17d22bba15001f/esp-hal-0.19.0/src/spi/master.rs:950:16
    |
950 |     pub struct SpiDma<'d, T, C, M, DmaMode>
    |                ^^^^^^
    = note: required for `Mutex<CriticalSectionRawMutex, SpiDma<'static, SPI2, Channel<0>, FullDuplexMode, Async>>` to implement `core::marker::Sync`
    = note: required for `&Mutex<CriticalSectionRawMutex, SpiDma<'static, SPI2, Channel<0>, FullDuplexMode, Async>>` to implement `core::marker::Send`
note: required because it appears within the type `SpiDevice<'_, CriticalSectionRawMutex, SpiDma<'static, SPI2, Channel<0>, FullDuplexMode, Async>, ...>`
   --> /home/being/.cargo/registry/src/index.crates.io-6f17d22bba15001f/embassy-embedded-hal-0.2.0/src/shared_bus/asynch/spi.rs:38:12
    |
38  | pub struct SpiDevice<'a, M: RawMutex, BUS, CS> {
    |            ^^^^^^^^^
note: required because it's used within this closure
   --> src/main.rs:253:72
    |
253 |         .start_app_core(unsafe { &mut *addr_of_mut!(APP_CORE_STACK) }, move || {
    |                                                                        ^^^^^^^
note: required by a bound in `esp_hal::cpu_control::CpuControl::<'d>::start_app_core`
   --> /home/being/.cargo/registry/src/index.crates.io-6f17d22bba15001f/esp-hal-0.19.0/src/soc/esp32s3/cpu_control.rs:280:12
    |
273 |     pub fn start_app_core<'a, const SIZE: usize, F>(
    |            -------------- required by a bound in this associated function
...
280 |         F: Send + 'a,
    |            ^^^^ required by this bound in `CpuControl::<'d>::start_app_core`
    = note: the full name for the type has been written to '/home/being/code/practice/rust/test-xtensa-nostd/target/xtensa-esp32s3-none-elf/debug/deps/test_xtensa_nostd-aafbfb69abc1d303.long-type-18372716027954553569.txt'
    = note: consider using `--verbose` to print the full type name to the console
    = note: the full name for the type has been written to '/home/being/code/practice/rust/test-xtensa-nostd/target/xtensa-esp32s3-none-elf/debug/deps/test_xtensa_nostd-aafbfb69abc1d303.long-type-16163152860988336495.txt'
    = note: consider using `--verbose` to print the full type name to the console
    = note: the full name for the type has been written to '/home/being/code/practice/rust/test-xtensa-nostd/target/xtensa-esp32s3-none-elf/debug/deps/test_xtensa_nostd-aafbfb69abc1d303.long-type-17612339641648107799.txt'
    = note: consider using `--verbose` to print the full type name to the console
    = note: the full name for the type has been written to '/home/being/code/practice/rust/test-xtensa-nostd/target/xtensa-esp32s3-none-elf/debug/deps/test_xtensa_nostd-aafbfb69abc1d303.long-type-15121438269329452012.txt'
    = note: consider using `--verbose` to print the full type name to the console
```